### ISSUE TITLE
InsiderMobileAdvancedNotification/InsiderPushNotification.h' file not found

### ISSUE THREAD

**Issue by tuannvitt** [useinsider/reactjs-sample#1]
Hi there, 
I have followed the instructions but still got this issue. Please help me troubleshoot and fix this issue. Appreciate that so much!
![Screen Shot 2020-12-08 at 09 40 53](https://user-images.githubusercontent.com/38986433/101431419-77c12d80-3939-11eb-8919-80445eced37a.png)

**Comment by tuannvitt** [comment]
![Uploading Screen Shot 2020-12-08 at 09.43.21.png…]()

**Comment by canberksinangil** [comment]
Hello @tuannvitt ,
could you elaborate more on this?

Steps I have followed > 
`git clone git@github.com:useinsider/reactjs-sample.git`
`cd reactjs-sample/InsiderDemo/`
`npm i`
`cd ios && pod install`
`xed .`
run the project

`pod --version
1.10.0`

`node --version
v15.1.0`

Let me know about how to reproduce.

**Comment by hwq0521** [comment]
Hi @tuannvitt , may I know how you solved this problem? I'm also facing this issues.
