### ISSUE TITLE
Technical support for Integrating insider service worker into an existing react app

### ISSUE THREAD

**Issue by rohan-buchner** [useinsider/reactjs-sample#2]
HI there.

I'm reaching out to any insider software engineer, because I've got to a bit of a wall in dealing with some of the Insider account managers. They keep linking me these docs. https://developers.useinsider.com/docs/native-opt-in-integration-with-vapid

But this does not cater for React/PSA style applications with existing service workers running at the root of the url... Our app also doesnt have sub paths like a server rendered app with server side routing (its just a SPA running out of S3), and the insider docs does not explain how to integrate the insider service worker with SPA style apps as stated before.

This is our production application.
https://scoot.co.za/

Our app makes use of this plugin to generate a service worker.
https://github.com/NekR/offline-plugin

I have merged the insider loading code into into our webpack plugins pipeline like this.
```
   
const OfflinePlugin = require('offline-plugin');   

/// other code

plugins: [
    new OfflinePlugin({
      relativePaths: false,
      publicPath: '/',
      appShell: '/',

      // No need to cache .htaccess. See http://mxs.is/googmp,
      // this is applied before any match in `caches` section
      excludes: ['.htaccess'],
      updateStrategy: 'changed',
      autoUpdate: 1000 * 60 * 2,

      caches: {
        main: [':rest:'],

        // All chunks marked as `additional`, loaded after main section
        // and do not prevent SW to install. Change to `optional` if
        // do not want them to be preloaded at all (cached only when first loaded)
        additional: ['*.chunk.js'],
      },

      // Removes warning for about `additional` section usage
      safeToUseOptionalCaches: true,

      ServiceWorker: {
        events: true,
        entry: path.join(process.cwd(), 'app/sw-handler.js'),
        navigateFallbackURL: '/',
      },
    })
]
```

where the `sw-handler.js` contains the following.
```
typeof importScripts === 'function' &&
  importScripts('https://api.useinsider.com/sw.js');
```

I have been told by jour account managers:
```

So we checked the integration that was done, 

As per our product team we were able to collect the tokens, but when testing we received double pushes. 

We don't think it will be possible to give support to a non-standard integration. 

Would you be able to follow the guide that has been shared? 
```

How can I resolve the above? Please help 🙏

**Comment by canberksinangil** [comment]
Hello @rohan-buchner, this is react-native demo project for Insider Mobile product. I think you are talking about our web product. Let me contact with the team and they will get back to you shortly 🤗
